# Configuration H2 simple pour Render.com (fallback)
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:ecampusnsia@gmail.com}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connection-timeout: 30000
          timeout: 30000
          write-timeout: 30000

# Configuration serveur
server:
  port: ${PORT:8080}

# Configuration notification
notification:
  email:
    from: ${EMAIL_FROM:ecampusnsia@gmail.com}
    from-name: "Université Aube Nouvelle - Notifications"

  whatsapp:
    web-api:
      enabled: ${WHATSAPP_ENABLED:false}
      url: ${WHATSAPP_API_URL:https://api.whatsapp.com}
    link-mode: true

  school:
    name: "Université Aube Nouvelle"

  scheduling:
    enabled: true
    batch-size: ${BATCH_SIZE:50}
    retry-attempts: ${RETRY_ATTEMPTS:3}
    retry-delay: ${RETRY_DELAY:5000}

# Logging optimisé
logging:
  level:
    com.school.notification: INFO
    org.springframework.mail: WARN
    org.hibernate: WARN
    root: INFO

# API Documentation
springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED:true}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}

# Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized