# Configuration spécifique pour Render.com
spring:
  datasource:
    # Render fournit DATABASE_URL au format postgresql://...
    # On utilise JDBC_DATABASE_URL qui sera défini manuellement
    url: ${JDBC_DATABASE_URL:jdbc:h2:mem:testdb}
    username: ${DATABASE_USER:sa}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC

  h2:
    console:
      enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:ecampusnsia@gmail.com}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connection-timeout: 30000
          timeout: 30000
          write-timeout: 30000

# Configuration serveur
server:
  port: ${PORT:8080}
  error:
    whitelabel:
      enabled: false

# Configuration notification
notification:
  email:
    from: ${EMAIL_FROM:ecampusnsia@gmail.com}
    from-name: "Université Aube Nouvelle - Notifications"

  whatsapp:
    web-api:
      enabled: ${WHATSAPP_ENABLED:false}
      url: ${WHATSAPP_API_URL:https://api.whatsapp.com}
    link-mode: true

  school:
    name: "Université Aube Nouvelle"

  scheduling:
    enabled: true
    batch-size: ${BATCH_SIZE:50}
    retry-attempts: ${RETRY_ATTEMPTS:3}
    retry-delay: ${RETRY_DELAY:5000}

# Logging optimisé pour Render
logging:
  level:
    com.school.notification: INFO
    org.springframework.mail: WARN
    org.hibernate: WARN
    org.springframework.web: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n"

# API Documentation
springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED:true}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    path: /swagger-ui.html

# Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: when-authorized